**NUMPY_PANDAS_PROJECT**

In [19]:
import pandas as pd
import numpy as np

In [42]:
df=pd.read_csv("ADANIENT.csv",header=2)

In [44]:
df.rename(columns={df.columns[0]:'Date'},inplace=True)

In [46]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

In [48]:
df=df.dropna(subset=['Date'])

In [49]:
df.columns=['Dates','Close','High','Low','Open','volume']

In [51]:
df.head(20)

        Dates        Close         High          Low         Open    volume
0  2026-03-16  1978.000000  1994.800049  1946.599976  1961.000000   1465828
1  2026-03-17  1975.400024  1990.000000  1945.000000  1989.900024   1268988
2  2026-03-18  2007.199951  2027.000000  1982.199951  1988.900024   1041095
3  2026-03-19  1936.800049  1988.599976  1930.000000  1984.000000   1510588
4  2026-03-20  1927.099976  1974.400024  1919.900024  1951.000000   1175662
5  2026-03-23  1833.000000  1910.099976  1820.500000  1910.000000   2370668
6  2026-03-24  1817.900024  1893.000000  1813.699951  1892.699951  11211381
7  2026-03-25  1886.599976  1911.000000  1839.199951  1847.900024   2537690
8  2026-03-27  1823.000000  1883.199951  1816.500000  1880.000000   2585257
9  2026-03-30  1758.800049  1837.800049  1753.000000  1810.000000   2825299
10 2026-04-01  1842.500000  1870.000000  1803.800049  1825.000000   2328166
11 2026-04-02  1834.199951  1842.900024  1770.099976  1805.000000   1830598
12 2026-04-06  1902.199951  1909.000000  1802.099976  1836.900024   3153437
13 2026-04-07  1882.099976  1904.599976  1865.000000  1890.000000   1566909
14 2026-04-08  2043.800049  2099.000000  1975.099976  2000.000000   4197831
15 2026-04-09  2040.500000  2065.000000  2010.300049  2039.800049   2481188
16 2026-04-10  2086.800049  2094.600098  2041.699951  2043.099976   1700162
17 2026-04-13  2129.000000  2159.000000  2000.199951  2010.199951   3729773
18 2026-04-15  2144.399902  2200.000000  2136.000000  2187.000000   1777925

In [52]:
df.columns

Index(['Dates', 'Close', 'High', 'Low', 'Open', 'volume'], dtype='object')

In [53]:
df.shape

(19, 6)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Dates   19 non-null     datetime64[ns]
 1   Close   19 non-null     float64
 2   High    19 non-null     float64
 3   Low     19 non-null     float64
 4   Open    19 non-null     float64
 5   volume  19 non-null     int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 1.0 KB

In [60]:

df['Dates'] = pd.to_datetime(df['Dates'])

In [61]:
df=df.sort_values(by='Dates')

In [62]:
df.head()

       Dates        Close         High          Low         Open   volume
0 2026-03-16  1978.000000  1994.800049  1946.599976  1961.000000  1465828
1 2026-03-17  1975.400024  1990.000000  1945.000000  1989.900024  1268988
2 2026-03-18  2007.199951  2027.000000  1982.199951  1988.900024  1041095
3 2026-03-19  1936.800049  1988.599976  1930.000000  1984.000000  1510588
4 2026-03-20  1927.099976  1974.400024  1919.900024  1951.000000  1175662

In [63]:
df.isnull().sum()

Dates     0
Close     0
High      0
Low       0
Open      0
volume    0
dtype: int64

In [64]:
df.describe()

,Dates,Close,High,Low,Open,volume
count,19,19.000000,19.000000,19.000000,19.000000,1.900000e+01
mean,2026-03-29 22:44:12.631578880,1939.436838,1976.526322,1903.731567,1939.600001,2.671497e+06
min,2026-03-16 00:00:00,1758.800049,1837.800049,1753.000000,1805.000000,1.041095e+06
25%,2026-03-21 12:00:00,1838.349976,1898.799988,1815.099976,1863.950012,1.538748e+06
50%,2026-03-30 00:00:00,1927.099976,1974.400024,1919.900024,1951.000000,2.328166e+06
75%,2026-04-07 12:00:00,2023.849976,2046.000000,1978.649963,1994.950012,2.705278e+06
max,2026-04-15 00:00:00,2144.399902,2200.000000,2136.000000,2187.000000,1.121138e+07
std,NaN,112.674911,106.925191,105.036912,98.376312,2.239028e+06

In [65]:
print("Max Price:",df['Close'].max())

Max Price: 2144.39990234375

In [68]:
print("Min Price:",df['Close'].min())

Min Price: 1758.800048828125

In [69]:
print("Average Price;",df['Close'].mean())

Average Price; 1939.4368382504113

In [72]:
price_array=df['Close'].values

In [74]:
np.mean(price_array)

np.float64(1939.4368382504113)

In [75]:
print("NumPy Mean:",np.mean(price_array))

NumPy Mean: 1939.4368382504113

In [76]:
print("Numpy Std Dev;",np.std(price_array))

Numpy Std Dev; 109.66970506288473

In [77]:
df['Daily_Return']=df['Close'].pct_change()

In [78]:
df[['Dates','Close','Daily_Return']].head()

       Dates        Close  Daily_Return
0 2026-03-16  1978.000000           NaN
1 2026-03-17  1975.400024     -0.001314
2 2026-03-18  2007.199951      0.016098
3 2026-03-19  1936.800049     -0.035074
4 2026-03-20  1927.099976     -0.005008

In [80]:
df['MA_10']=df['Close'].rolling(10).mean()
df['MA_20']=df['Close'].rolling(20).mean()
df[['Close','MA_10','MA_20']].head()

         Close  MA_10  MA_20
0  1978.000000    NaN    NaN
1  1975.400024    NaN    NaN
2  2007.199951    NaN    NaN
3  1936.800049    NaN    NaN
4  1927.099976    NaN    NaN

In [83]:
recent=df[df['Dates']>'2023-01-01']
recent.head(20)

,Dates,Close,High,Low,Open,volume,Daily_Return,MA_10,MA_20
0,2026-03-16,1978.000000,1994.800049,1946.599976,1961.000000,1465828,NaN,NaN,NaN
1,2026-03-17,1975.400024,1990.000000,1945.000000,1989.900024,1268988,-0.001314,NaN,NaN
2,2026-03-18,2007.199951,2027.000000,1982.199951,1988.900024,1041095,0.016098,NaN,NaN
3,2026-03-19,1936.800049,1988.599976,1930.000000,1984.000000,1510588,-0.035074,NaN,NaN
4,2026-03-20,1927.099976,1974.400024,1919.900024,1951.000000,1175662,-0.005008,NaN,NaN
5,2026-03-23,1833.000000,1910.099976,1820.500000,1910.000000,2370668,-0.048830,NaN,NaN
6,2026-03-24,1817.900024,1893.000000,1813.699951,1892.699951,11211381,-0.008238,NaN,NaN
7,2026-03-25,1886.599976,1911.000000,1839.199951,1847.900024,2537690,0.037791,NaN,NaN
8,2026-03-27,1823.000000,1883.199951,1816.500000,1880.000000,2585257,-0.033711,NaN,NaN
9,2026-03-30,1758.800049,1837.800049,1753.000000,1810.000000,2825299,-0.035217,1894.380005,NaN
10,2026-04-01,1842.500000,1870.000000,1803.800049,1825.000000,2328166,0.047589,1880.830005,NaN
11,2026-04-02,1834.199951,1842.900024,1770.099976,1805.000000,1830598,-0.004505,1866.709998,NaN
12,2026-04-06,1902.199951,1909.000000,1802.099976,1836.900024,3153437,0.037073,1856.209998,NaN
13,2026-04-07,1882.099976,1904.599976,1865.000000,1890.000000,1566909,-0.010567,1850.739990,NaN
14,2026-04-08,2043.800049,2099.000000,1975.099976,2000.000000,4197831,0.085915,1862.409998,NaN
15,2026-04-09,2040.500000,2065.000000,2010.300049,2039.800049,2481188,-0.001615,1883.159998,NaN
16,2026-04-10,2086.800049,2094.600098,2041.699951,2043.099976,1700162,0.022691,1910.050000,NaN
17,2026-04-13,2129.000000,2159.000000,2000.199951,2010.199951,3729773,0.020222,1934.290002,NaN
18,2026-04-15,2144.399902,2200.000000,2136.000000,2187.000000,1777925,0.007233,1966.429993,NaN

In [85]:
high_return=df[df['Daily_Return']>0.02]
high_return[['Dates','Daily_Return']]

        Dates  Daily_Return
7  2026-03-25      0.037791
10 2026-04-01      0.047589
12 2026-04-06      0.037073
14 2026-04-08      0.085915
16 2026-04-10      0.022691
17 2026-04-13      0.020222

In [87]:
df['Month']=df['Dates'].dt.month
monthly_avg=df.groupby('Month')['Close'].mean()
monthly_avg

Month
3    1894.380005
4    1989.499986
Name: Close, dtype: float64

In [88]:
df.to_csv("final_output.csv",index=False)